### ISSUE TITLE
Improve definitions of 'spectral window range maximum' & 'spectral window range minimum'

### ISSUE THREAD

**Issue by StroemPhi** [NFDI4Chem/VibrationalSpectroscopyOntology#131]
Within our 2024.05.17 dev call, we discussed that 'spectral window range maximum' (VIBSO:0000015) & 'spectral window range minimum' (VIBSO:0000016) must be considered fixed parameters of the Raman spectrometer (specifically the detector), which are part of the metadata of a Raman dataset.

- [x] Check the ISO docs for definitions of these parameters
- [ ] rewrite definitions accordingly
- [ ] maybe subsume under a more fitting parent class

**Comment by Zack-83** [comment]
I just discussed with @RainerStosch .
Physically the spectral window is determined by a combination of instrumental parameter, such as the excitation wavelength and several properties of both the grating and of the detector.
The grating separates spatially the different wavelengths.
The detector captures a part of them and responds to them according to the own response function, which is significantly different from zero within its own detection range.
The spectral window recorded in an experiment is given by a subset of the "spread window" by the grating and of the "response window" by the detector, thus narrower than both.
The experimentalist normally chooses the center of the spectral window by rotating the grating; the width/minimum/maximum are then calculated by the software on the basis of the spectral resolution of the grating and of the detector width. (If it is not enough, several overlapping windows are combined to cover the entire desired spectral range, similarly to a panorama photo.)

Conclusion: we suggest to keep it simple and leave the definitions as they are.
