### ISSUE TITLE
misleading acronym

### ISSUE THREAD

**Issue by tilfischer** [NFDI4Chem/VibrationalSpectroscopyOntology#18]
The acronym used for the vibrational spectroscopy ontology ViSprO is highly misleading and should be changed. Especially in the case-insensitive versions such as VISPRO or vispro, it might be read as VIS-PRO, while vibrational spectroscopy does not use visible light.

**Comment by tilfischer** [comment]
Possible alternative, also because of some other ongoing project, could be VibSpecO (VIBSPECO, vibspeco).

**Comment by tilfischer** [comment]
I am fine with both suggestions, vibso is also a good alternative to vispro.

**Comment by StroemPhi** [comment]
@sneumann VSO would be too short imo, and I like acronyms that can be read instead of saying the letters out loud. But that's just me. Feel free to trow another alternative in the ring that we can vote on.

**Comment by tilfischer** [comment]
For these reasons, I think we already agreed on VIBSO.
