### ISSUE TITLE
[Docs] Correction of small spelling mistakes and broken links

### ISSUE THREAD

**Issue by hujo91** [NFDI4Chem/VibrationalSpectroscopyOntology#22]
The following spelling mistakes should be corrected:
- [x] "**virational** spectroscopy" to "vibrational spectroscopy" in last line of the 2nd paragraph "[Ontological Dependencies](https://nfdi4chem.github.io/VibrationalSpectroscopyOntology/domain_definition/)"
- [x] "V**i**SBO" to "VIBSO" in penultimate line in section "[Importing terms](https://nfdi4chem.github.io/VibrationalSpectroscopyOntology/ntr_workflow/)"

The following links should be checked:
- [x] [vispro_terms.tsv template](https://github.com/NFDI4Chem/VibrationalSpectroscopyOntology/blob/main/src/templates/vispro_terms.tsv) in section "[Adding New Terms to the TSV Template](https://nfdi4chem.github.io/VibrationalSpectroscopyOntology/ntr_workflow/)" -> correction maybe [vibso_terms.tsv template](https://github.com/NFDI4Chem/VibrationalSpectroscopyOntology/blob/main/src/templates/vibso_terms.tsv)
- [x] [pac 2019-0203 terms.yaml](https://nfdi4chem.github.io/VibrationalSpectroscopyOntology/domain_definition/pac%202019-0203%20terms.yaml) in section "[Ontological Dependencies](https://nfdi4chem.github.io/VibrationalSpectroscopyOntology/domain_definition/)" -> correction maybe: [pac 2019-0203 terms](https://doi.org/10.1515/pac-2019-0203)

**Comment by StroemPhi** [comment]
Thank you @hujo91 :wink:
