### ISSUE TITLE
[NTR] add "objective magnification"

### ISSUE THREAD

**Issue by StroemPhi** [NFDI4Chem/VibrationalSpectroscopyOntology#24]
For new term requests, please provide the following information:

## Preferred term label

objective magnification factor setting

## Synonyms

objective magnification

## Textual definition

A setting datum that specifies the magnification factor of the objective collecting the scattered light.

## Suggested parent term
[IAO:setting datum](https://terminology.nfdi4chem.de/ts/ontologies/vibso/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FIAO_0000140)

## Attribution

ORCID:0000-0001-7694-5519

**Comment by StroemPhi** [comment]
@Zack-83 am I understanding this correctly that this magnification is a device setting that is made before the expetiment? Can you please provide an example, which we could add to the term?

**Comment by StroemPhi** [comment]
[95eb688](https://github.com/NFDI4Chem/VibrationalSpectroscopyOntology/commit/95eb688e9aa64b051d3dda8bd222eef55f14c274) & [09a5a08](https://github.com/NFDI4Chem/VibrationalSpectroscopyOntology/commit/09a5a0828a09a7145c8df10f5cb0dc13eed2bffd) must be ignored as they were accidentally pushed to an outdate branch, which was now deleted

**Comment by Zack-83** [comment]
> @Zack-83 am I understanding this correctly that this magnification is a device setting that is made before the expetiment? Can you please provide an example, which we could add to the term?

Yes, it is an experimental setting which has also consequences on resolution, signal-to-noise ratio etc. As value I expect simply "100 x", "40 x".

**Comment by StroemPhi** [comment]
Based on the [Parameters_and_Units_IR_and_Raman_for_VIBSO.xlsx](https://github.com/NFDI4Chem/VibrationalSpectroscopyOntology/blob/main/docs/Parameters_and_Units_IR_and_Raman_for_VIBSO.xlsx) it seems best to add the synonym `magnification` and maybe `magnification setting` for this setting.
