### ISSUE TITLE
think about hwo to best obsolete terms defined in the TSV

### ISSUE THREAD

**Issue by StroemPhi** [NFDI4Chem/VibrationalSpectroscopyOntology#27]
There will be the cases, when a term previously defined in the TSV template will turn out to be wrong or not usefull and should thus be deprecated. We will not delete any terms as is an ontology development best practice. We thus need a workflow that adresses term deprecation. Maybe this is done fisrt in a pragmatic way by adding columns for needed deprecation annotations. Later deprecated entities might be moved into another TSV for better maintainability of the main TSV.

**Comment by StroemPhi** [comment]
@Zack-83 totally agree as long as we are in alpha stage. But still we should discuss these things first among the developers first. As in this case these different classes where not representing the same concepts.

**Comment by Zack-83** [comment]
Yes. This is an argument for an additional column (not only "mark for deprecation", but also "explain why")

**Comment by StroemPhi** [comment]
Yes, deprecation columns include one for the reason, one for the term(s) that should be used instead and one for holding the owl:deprecated boolean value. However, when I say we should discuss it first, I mean that this should not happen in the TSV itself, but in issues here. THe TSV is just another means of editing the ontology without having to use Protégé.

**Comment by StroemPhi** [comment]
the deprecation columns have been integrated in #38
