### ISSUE TITLE
[NTR] add "incident light power"

### ISSUE THREAD

**Issue by Zack-83** [NFDI4Chem/VibrationalSpectroscopyOntology#29]
## Preferred term label

incident light power datum

## Synonyms

excitation light power; light power on the sample

## Textual definition

A scalar measurement datum that is the result of measuring the incoming light power before the sample holder and which depends on the laser power and on the dispersive behaviour of the filters and optical components.

## Suggested parent term

[iao:scalar measurement datum](https://terminology.nfdi4chem.de/ts/ontologies/iao/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FIAO_0000032)

## Examples
200 mW

## Attribution

ORCID:0000-0001-7694-5519

**Comment by StroemPhi** [comment]
@Zack-83 is [this](https://github.com/NFDI4Chem/VibrationalSpectroscopyOntology/blob/main/data_examples/Raman_example_data_NEST/Raman%20spectroscopy%20aqueous%20solution%20setup.yml#L54) an example value and its key thus a synonym for the requested term?

**Comment by Zack-83** [comment]
yes

**Comment by StroemPhi** [comment]
@Zack-83 but what I find a bit odd is the fact that in this example we have a range as a value for the incident power. I thought it would be meassured more precisely.

**Comment by StroemPhi** [comment]
According to our [call from the 10.03.22023](https://docs.google.com/document/d/1iPPjRbgpAmd5Iz6-8E0IKqZTxO8Ggd4uJCmP26GypBA) we need to add a comment that the laser power measurement from which this datum is the output off needs to be defined in more detail later. This corresponds with the phrase in the current definition "depends on the laser power and on the dispersive behaviour of the filters and optical components". So we would need to take into account the area of analysis when referring to the energy at the sample as well as the volume of the energy beam at the sample.
