### ISSUE TITLE
[NTR] add "number of accumulations"

### ISSUE THREAD

**Issue by Zack-83** [NFDI4Chem/VibrationalSpectroscopyOntology#30]
## Preferred term label

"number of accumulations"

## Synonyms

"number of acquisitions"

## Textual definition

The number of acquisitions on the same location, without position change. (Relevant to improve the S/N ratio.)

## Suggested parent term

Please look in the hierarchy in a browser such as the [NFDI4Chem TS](https://terminology.nfdi4chem.de/ts/ontologies/vibso)

## Attribution

ORCID:0000-0001-7694-5519

**Comment by StroemPhi** [comment]
@Zack-83 so the "number of repetitions" differs from the "number of scans" in that the former refers to the scan of a certain, not changing portion/location of the sample, whereas the latter refers to the scan of the sample in general? Like I could have 5 scans of the sample's region A (x=0.5 cm, y=0.5 cm) and 5 scans of the sample's region B (x=0.5 cm, y=0.5 cm), and then the number of scans would be 10 but the number of repititions 2x5?

**Comment by StroemPhi** [comment]
@Zack-83 in the above PR I added the total integration time setting. I put the PR in draft mode, as I need to know first if "number of scans" is really the same as the "number of repitions" you requested here.

**Comment by StroemPhi** [comment]
Is "Number Of Accumulations" (see https://github.com/NFDI4Chem/VibrationalSpectroscopyOntology/blob/main/data_examples/Raman_example_data_IPHT/metadata_device/AT2_001%20Information.txt#L26) a synonym for number of scans/repetitions?

**Comment by Zack-83** [comment]
Not exactly... Sometimes can multiple acquisitions be performed on a single pixel before completing a scan. I don't know, which consequences it has on the result of a measurement

**Comment by StroemPhi** [comment]
Ok, but how about "number of scans" and "number of repetitions", are these synonyms?

**Comment by Zack-83** [comment]
We talked about that.

"Number of scans / repetitions" (repeated acquisition of full images) might be interesting to detect time-dependent effects, but belongs essentially to the experimental design and is not typical for Raman. Therefore we don't need it any more.

"Number of accumulations / acquisitions" is the number of repetitions on a single pixel. This is relevant to improve the S/N ratio. That can be renamed and must remain.

The "total integration time" should be replaced with the "single integration time" which is the "primary" variable".

Sorry for the chaos

**Comment by StroemPhi** [comment]
@Zack-83 no problems that helps alöot and makes thing much clearer :)
