### ISSUE TITLE
[NTR] add "spectral window range: minimum" and "spectral window range: maximum"

### ISSUE THREAD

**Issue by Zack-83** [NFDI4Chem/VibrationalSpectroscopyOntology#31]
## Preferred term label

spectral window range minimum and spectral window range maximum

## Synonyms

acquisition band minimum & acquisition band maximum

## Textual definition

A data item that is the part of a Raman spectrum which represents the maximum/minimum wavenumber included in the spectrum and which is calculated from the windows size and window center.

## Suggested parent term

[IAO:data item](https://terminology.nfdi4chem.de/ts/ontologies/vibso/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FIAO_0000027)

## Examples
spectral window range minimum = 210 cm^−1 
spectral window range maximum = 1960 cm^−1 

## Attribution

ORCID:0000-0001-7694-5519

**Comment by StroemPhi** [comment]
@Zack-83 is this a quality/attribute of the spectrum pr a setting of the spectroscopy?

**Comment by Zack-83** [comment]
It is an attribute of the spectrum.

**Comment by StroemPhi** [comment]
![grafik](https://user-images.githubusercontent.com/56996739/212057454-48d89619-f80d-481c-93c1-8b973ea5e39f.png)
@Zack-83 do I understand you correctly, that the two terms you request here are parts of the data item (information) that is the Raman spectrum and which refer to the lower and upper bounds of the X-axis which represents the wavenumber?

And if so, my next question would be: Are the "window size" and "window center" from which they get calculated the output of a data transformation on the initially detected signal or are thy determined by a setting of the Raman spectrometer?

**Comment by Zack-83** [comment]
Yes, "minimum" and "maximum" belong to the spectrum and refer to that axis in the diagram. (Of course it is not the spacial X-axis, but the horizontal axis of a spectrum diagram.)

Even "window size" and "window center", expressed as wavenumbers, are not really primitive instrumental parameter; to my knowledge they are calculated based on window center wavelength, excitation wavelength and groove density.

@RainerStosch @Stefano-Luin feel free to correct / complement.

**Comment by StroemPhi** [comment]
If I understand correctly, we then also need to mint "window size as wavelength" and "window center wavelength", right? 
And by looking at the data example you provided, I would assume that an example of the former is https://github.com/NFDI4Chem/VibrationalSpectroscopyOntology/blob/main/data_examples/Raman_example_data_NEST/Raman%20spectroscopy%20aqueous%20solution%20setup.yml#L29 and of the latter https://github.com/NFDI4Chem/VibrationalSpectroscopyOntology/blob/main/data_examples/Raman_example_data_NEST/Raman%20spectroscopy%20aqueous%20solution%20setup.yml#L28. Is that correct?

**Comment by Zack-83** [comment]
Yes, there they are.  
Probably we don't need to mint everything... It depends on the scope.  
If the scope is to make experimental results searchable, comparable and combinable with others, then we need a limited amount of parameters and thus of classes.  
If the scope is to document the experimental procedure to make it reproducible, then we need to define the settings in a way which is univoquely implementable for present, past and future setups.  
I suppose that the first scope is easier to implement.

**Comment by StroemPhi** [comment]
The reason for me asking to also mint these is rooted in the textual definition you provided: "[...] calculated from window size and window center." 

Regarding VIBSO's scope, so far we have it defined broad enough [here](https://nfdi4chem.github.io/VibrationalSpectroscopyOntology/domain_definition/) to also include the reproducability aspect, which I think is implied in the IR of FAIR data. But VIBSO's development is an incremental process and to be also a managable one, I agree that we need to focus on one thing after another, e.g. findability first. For this it is necessary to regularly check and update the [competency questions](https://nfdi4chem.github.io/VibrationalSpectroscopyOntology/competency_questions/), as they can be used as kind of unit tests for the expressiveness of the ontology. So I'd love to get feedback from you with regard to what kind of questions do you experts consider the most important atm. Like when you say "relevant for searching/comparing", please try to formulate a competency question. Maybe in this example it would be something along the lines of: "What is the window range minumum and maximum of the Raman spectrum produced by the Raman assay X that implements Raman spectroscopy method Y?"

related to: #54

**Comment by StroemPhi** [comment]
To switch the focus back on the two terms requested in this issue, is this [aquisition band](https://github.com/NFDI4Chem/VibrationalSpectroscopyOntology/blob/main/data_examples/Raman_example_data_NEST/Raman%20spectroscopy%20aqueous%20solution%20setup.yml#L53) parameter providing examples for the minimum (210 cm^−1) and maximum (1960 cm^−1) spectral window range?

**Comment by Zack-83** [comment]
> To switch the focus back on the two terms requested in this issue, is this [aquisition band](https://github.com/NFDI4Chem/VibrationalSpectroscopyOntology/blob/main/data_examples/Raman_example_data_NEST/Raman%20spectroscopy%20aqueous%20solution%20setup.yml#L53) parameter providing examples for the minimum (210 cm^−1) and maximum (1960 cm^−1) spectral window range?

Exactly.

As you can see, my description example has potential for improvement :)

I agree with you, we should have a look at the competency questions. Together with our experts.

I tried to reconstruct the formulas to calculate the minimum and maximum wavenumbers of the spectral window:

$$ \bar\nu_\min = \frac{1}{\lambda_\mathrm{exc}} - \frac{1}{\lambda_\mathrm{center}+\Delta\lambda/2} $$

$$ \bar\nu_\max = \frac{1}{\lambda_\mathrm{exc}} - \frac{1}{\lambda_\mathrm{center}-\Delta\lambda/2} $$

I beg the experts to check.

**Comment by StroemPhi** [comment]
Hi @Zack-83, 
in #55 I added the requested two terms, without introducing the possible classes on which they are based. But I added an editor note referring to the possible need for minting these later.
