### ISSUE TITLE
[NTR] add dimensional screen parameteres of Raman spectral imaging

### ISSUE THREAD

**Issue by Zack-83** [NFDI4Chem/VibrationalSpectroscopyOntology#32]
## context / use case
In [Raman spectral imaging](https://terminology.nfdi4chem.de/ts/ontologies/chmo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCHMO_0000056), multiple Raman spectroscopy measurements with the same configuration are performed in different spots of a sample within a predefined grid that covers a certain region of interest. The resulting spectra are then integrated into Raman images (also known as maps) that contain the variations in spectral information at different points on, or inside, the analysed part of the sample. The predefined sampling grid that makes up this region of interest can either be one-, two- or three-dimensional. To cover this ontologically, we need terms that represent the settings entered into the device controller which determine such a sampling grid. These terms are: 

## requested new terms
* label: region of interest 
   * text def.: A site that refers to a user-defined portion of the image area in which data will be acquired. The remainder of the image area will be discarded. 
      * def. source: [CHARISMA:Q57](https://wiki.charisma.ideaconsult.net/wiki/Item:Q57)
   * synonyms: imaging region of interest, ROI
   * subclass of: [BFO:0000029 (site)](https://terminology.nfdi4chem.de/ts/ontologies/vibso/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBFO_0000029)
   * skos:exactMatch: [reproduceme:ROI](https://w3id.org/reproduceme#ROI), [NCIT:C85402](http://purl.obolibrary.org/obo/NCIT_C85402)

* label: region of interest width
   * text def.: A setting datum that specifies the width (horizontal length) of the region of interest. 
   * synonyms: ROI width, ROI horizontal length
   * subclass of: [IAO:0000140 (setting datum)](https://terminology.nfdi4chem.de/ts/ontologies/vibso/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FIAO_0000140)
* label: region of interest height
   * text def.: A setting datum that specifies the height (vertical length) of the region of interest.  
   * synonyms: ROI height, ROI vertical length
   * subclass of: [IAO:0000140 (setting datum)](https://terminology.nfdi4chem.de/ts/ontologies/vibso/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FIAO_0000140)
* label: region of interest depth 
   * text def.: A setting datum that specifies the depth (length in the z direction) of the region of interest.
   * synonyms: ROI depth, ROI length in the z direction
   * subclass of: [IAO:0000140 (setting datum)](https://terminology.nfdi4chem.de/ts/ontologies/vibso/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FIAO_0000140)

* label: horizontal point distance
   * text def.: A setting datum that specifies the equal distance which the incident light beam will be moved horizontally on a given sample within the region of interest after each measurement, when performing a spatially resolved spectroscopy.
   * synonyms: horizontal sampling pace, horizontal sampling step, horizontal voxal distance, horizontal measurement distance
   * subclass of: [IAO:0000140 (setting datum)](https://terminology.nfdi4chem.de/ts/ontologies/vibso/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FIAO_0000140)
* label: vertical point distance
   * text def.: A setting datum that specifies the equal distance which the incident light beam will be moved vertically on a given sample within the region of interest after each measurement, when performing a spatially resolved spectroscopy.
   * synonyms: vertical sampling pace, vertical sampling step, vertical voxal distance, vertical measurement distance
   * subclass of: [IAO:0000140 (setting datum)](https://terminology.nfdi4chem.de/ts/ontologies/vibso/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FIAO_0000140)
* label: focal point distance
   * text def.: A setting datum that specifies the equal distance which the incident light beam will moved on the focal plane within the region of interest, when performing a spatially resolved spectroscopy.
   * synonyms: focal sampling pace, focal sampling step, focal voxal distance, focal measurement distance
   * subclass of: [IAO:0000140 (setting datum)](https://terminology.nfdi4chem.de/ts/ontologies/vibso/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FIAO_0000140)

* label: number of horizontal measurments
   * text def.: A setting datum that specifies how many equally configured measurements of a sample are to be performed in the horizontal direction (on the x plane) of a certain region of interest. Together with the horizontal point distance, this setting defines the region of interest width.
   * synonyms: number of points in the X direction, number of points per line
   * subclass of: [IAO:0000140 (setting datum)](https://terminology.nfdi4chem.de/ts/ontologies/vibso/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FIAO_0000140)
* label: number of vertical measurments
   * text def.: A setting datum that specifies how many equally configured measurements of a sample are to be performed in the vertical direction (on the y plane) of a certain region of interest. Together with the vertical point distance, this setting defines the region of interest height.
   * synonyms: number of points in the Y direction, number of lines per layer
   * subclass of: [IAO:0000140 (setting datum)](https://terminology.nfdi4chem.de/ts/ontologies/vibso/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FIAO_0000140)
* label: number of transversal measurments
   * text def.: A setting datum that specifies how many equally configured measurements of a sample are to be performed in the transversal direction (on the z plane) of a certain region of interest. 
   Together with the focal point distance, this setting defines the region of interest depth.
   * synonyms: number of points in the Z direction, number of layers per acquisition
   * subclass of: [IAO:0000140 (setting datum)](https://terminology.nfdi4chem.de/ts/ontologies/vibso/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FIAO_0000140)

**Comment by StroemPhi** [comment]
@Zack-83 please provide more context what you mean, as the textual definitions are not comprehensible enough. They should be understandable by non Raman expersts as well. Am I assuming correctly, that with "region of interest" you are refering to a section of the sample with 3 dimensions (width X, length Y, depth Z)? So we need to be able to say that the part of the sample that was assayed has a specific spacial extend (e.g. 3.0 x 4.0 x 5.0 mm) and that this assayed section was observed with a certain resolution?

**Comment by Zack-83** [comment]
Exactly. Of course the wording can be improved.  
We can define it "The extension of part of the sample essayed in the X direction", etc.

For each dimension, we have three nonindependent parameters: extension, number of points, resolution = n°points/width.  
(Of course, neglecting nonrectangular sampling "gratings")

**Comment by Zack-83** [comment]
We decided to simplify the picture. We drop the two "extensive" quantities (nr points and length) and reciprocate the definition of resolution. The pull request comes in few minutes.

**Comment by StroemPhi** [comment]
In order to find the right parent for these classes and thus also improve their definition, I need to know what kind of entity this is. Is it a setting, or a quality (in terms of specification) of the spectrometer?

**Comment by Zack-83** [comment]
It is a property of a spectrum, which can be used to select or compare data. Apparently no primary variable / setting, which may be calculated from spatial width and number of points (@RainerStosch , do you confirm?)

**Comment by StroemPhi** [comment]
OK, I was asking because after reading https://en.wikipedia.org/wiki/Diffraction-limited_system, due to the current textual definition as proposed in the associated PR speaking of "distance" and due to the provided formula in the editor note containing only qualities (wavelength and numerical aperture (NA)), I interpret these three distances also as qualities of the spectroscope (as  [obi:device setting](https://www.ebi.ac.uk/ols/ontologies/obi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0000654) subclasses to be precise). 
Also the current textual definiton only states that they must always be bigger than the "minimum resolvable distance as defined by the Abbe's criterion". But it does not state how the difference to that minimum comes into being. And it is this difference, which imo determines this quality. So the question to be answered is this: Does the Raman specialist specify this distenace at some point directly or indirectly?

**Comment by StroemPhi** [comment]
Ig we want to be ontologically precise we will need to also define the "region of interest" as a entity of itself (see: https://wiki.charisma.ideaconsult.net/wiki/Item:Q57) which has the hight, width and depth used here as attributes.

**Comment by Zack-83** [comment]
> 



> If we want to be ontologically precise we will need to also define the "region of interest" as a entity of itself (see: https://wiki.charisma.ideaconsult.net/wiki/Item:Q57) which has the hight, width and depth used here as attributes.

OK --> https://github.com/NFDI4Chem/VibrationalSpectroscopyOntology/pull/62/commits/782e57ce81bcd23afbf9dca90ef1936f482dfc82
