### ISSUE TITLE
[NTR] add "signal-to-noise ratio"

### ISSUE THREAD

**Issue by Zack-83** [NFDI4Chem/VibrationalSpectroscopyOntology#33]
For new term requests, please provide the following information:

## Preferred term label

signal-to-noise ratio

## Synonyms

...

## Textual definition

The ratio between the height of the lowest relevant peak and the root-mean-square height of the background signal. It requires the (somehow arbitrary) choice about what is or is not a relevant signal.

## Suggested parent term

Please look in the hierarchy in a browser such as the [NFDI4Chem TS](https://terminology.nfdi4chem.de/ts/ontologies/vibso)

## Examples

Please provide a more detailed description that examplifies how the term is supposed to be used, in terms of what it is suppose to repesent (e.g. a concept or a relation).

## Attribution

ORCID:0000-0001-7694-5519; ORCID:0000-0002-2239-3955

**Comment by StroemPhi** [comment]
@Zack-83 does any one of the results in [this query](https://www.ebi.ac.uk/ols/search?q=signal+to+noise+ratio&groupField=iri&start=0&ontology=afo) provide a class that expresses what you need?

**Comment by StroemPhi** [comment]
If https://www.ebi.ac.uk/ols/ontologies/stato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FSTATO_0000050 would also fit, I'd rather opt for reusing/importing this one instead of an AFO term.

**Comment by Zack-83** [comment]
I agree with you that the `obo:STATO_0000050` is the most suitable term.

https://www.ebi.ac.uk/ols/search?q=%22signal+to+noise+ratio%22

**Comment by StroemPhi** [comment]
Then I will add this now in a PR, which can also serve as an example for you to see how to import external terms.
