### ISSUE TITLE
[Docs] Remove fields whose content is not well-defined

### ISSUE THREAD

**Issue by Zack-83** [NFDI4Chem/VibrationalSpectroscopyOntology#35]
Some fields are not well defined and include multiple information, most of which already included elsewhere: "vibrational spectrometer configuration specification"; "Raman spectrometer configuration"

I suggest to remove them.

**Comment by StroemPhi** [comment]
These two classes (not fields) exist indepently from each other as a Raman spectrometer configuration can have different aspects/parts than a vibrational spectrometer configuration. After all we want this to be a vibrational spectroscopy ontology and not just a Raman specific one.

**Comment by StroemPhi** [comment]
Also "vibrational spectrometer configuration specification" (which should better be renamed to "vibrational spectrometer configuration setting" to be in line with the other subclasses of IAO:setting datum) is not the the same as a "vibrational spectrometer configuration" (which we didn't mint yet) as the former refers to the information entered into the device or stored in some config files that determines the actually physical qualities of the spectrometer.
