### ISSUE TITLE
[Docs] Remove classes not relevant for data search

### ISSUE THREAD

**Issue by Zack-83** [NFDI4Chem/VibrationalSpectroscopyOntology#36]
Some fields, although instrumentally relevant, do not seem useful to search for existing data or may be superseded by other "better centered" fields:

"horizontal shift speed setting"; "vertical shift speed setting"; --> may be substituted by integration time and spatial resolution

"preamplifier gain setting" --> is normally adjusted manually to prevent CCd saturation, has surely an effect on the signal-to-noise ratio but not on findability or comparability of spectra

**Comment by StroemPhi** [comment]
"horizontal shift speed setting"; "vertical shift speed setting" - If the labels of these classes are not good enough, then we should change them accordingly. I took them from the initial dataset shared with us. I will make seperate issues for each term we have so far, so we can discuss the term in its individual issue.

With reagrd to the "preamplifier gain setting" class, again this came from an example dataset, so it seemed relevant.

**Comment by StroemPhi** [comment]
The mentioned classes now have their own issues (#41 & #42), so we can discuss their definition and relevance there more specifically.
