### ISSUE TITLE
[NTR] add "exposure time setting"

### ISSUE THREAD

**Issue by StroemPhi** [NFDI4Chem/VibrationalSpectroscopyOntology#40]
## Preferred term label
exposure time setting

## Synonyms

(e.g., Absent spleen)

## Textual definition

A setting datum that specifies the duration in which an electromagnetic radiation beam is exposed to / recorded by a photosensor.

## Suggested parent term

[IAO:setting datum](https://terminology.nfdi4chem.de/ts/ontologies/vibso/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FIAO_0000140)

## Attribution
ORCID:0000-0002-1595-3213

**Comment by StroemPhi** [comment]
This issue was created retrospectivly to have a term tracker item to link to within the ontology, for future discussions about and the tracking of possible changes of this term.

**Comment by StroemPhi** [comment]
@Zack-83 is the "single integration time" you refer to in #30 wrt "total integration time" the same as / a synonym of this "exposure time setting".

**Comment by StroemPhi** [comment]
Proposal to change the label an definition to this:
**label**: integration time setting
**definition**: A setting datum that specifies the length of time that a photo detector is allowed to collect photons before passing the accumulated charge to the A/D converter for processing. The minimum integration time is the shortest integration time the device supports and is dependent on how fast the detector can read out all of the pixel information. Integration time should not be confused with data transfer speed.
**definition source**: https://www.sciencedirect.com/topics/mathematics/time-integration

**Comment by Zack-83** [comment]
I agree. @RainerStosch you too?

**Comment by Zack-83** [comment]
> @Zack-83 is the "single integration time" you refer to in #30 wrt "total integration time" the same as / a synonym of this "exposure time setting".

Yes, it is
