### ISSUE TITLE
[Docs] add other creators and contributors to the ontology metadata

### ISSUE THREAD

**Issue by StroemPhi** [NFDI4Chem/VibrationalSpectroscopyOntology#79]
Currently only I am listed as creator, but our domain experts and the other VIBSO devs need to be added as well off course!

**Comment by Zack-83** [comment]
Of course. In which source file?

**Comment by StroemPhi** [comment]
@Zack-83 in the [src/ontology/vibso-edit.owl](https://github.com/NFDI4Chem/VibrationalSpectroscopyOntology/blob/main/src/ontology/vibso-edit.owl) using dcterm:contributor please. If we use this over dct:creator for all of us, then we don't have to worry about any concrete attribution details. My ORCID in the metadata shown in the Terminology service comes from the configuration YAML we need for the indexing of VIBSO. I will delete it from there and only leave NFDI4Chem as a creator.
